if(EXISTS "/home/rabbany/Desktop/LumaWall/build_release/src/tests/lumawall_x11_tests[1]_tests.cmake")
  include("/home/rabbany/Desktop/LumaWall/build_release/src/tests/lumawall_x11_tests[1]_tests.cmake")
else()
  add_test(lumawall_x11_tests_NOT_BUILT lumawall_x11_tests_NOT_BUILT)
endif()
